config/routes.rb
Rails.application.routes.draw do

  root to: 'visitors#index'
  devise_for :users, controllers: {registrations: 'registrations'}
  resources :users

  resources :clientes
  devise_for :clientes
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new

        if user.role == "gerente"
            can :manage, :all

        elsif user.role == "administrador"
            alias_action :create, :read, :update, :to => :cru
            can :cru, Cliente

        elsif user.role == "usuario"
            alias_action :create, :read, :to => :cr
            can :cr, Cliente
        end
  end
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  # para que acepte los parametros, agregar  el before filter
  # issue https://github.com/ryanb/cancan/issues/835#issuecomment-18663815

  before_filter do
    resource = controller_name.singularize.to_sym
    method = "#{resource}_params"
    params[resource] &&= send(method) if respond_to?(method, true)
  end

  #agregado por requisito de Devise
  #deshabilitar para permitir el registro del primer usuario
  #si se quiere separar la validacion por controlador
  #se debe agregar before_filter :authenticate_user!, :except => [:some_action_without_auth]
  #sino, lo manejamos de forma general
  
  #before_action :authenticate_user!, :except => [:find]
 
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :password, :remember_me) }
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :role, :email, :password, :password_confirmation, :current_password)}
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController

    load_and_authorize_resource
    before_action :authenticate_user!
  
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @clientes = Cliente.all
    respond_with(@clientes)
  end

  def show
    respond_with(@cliente)
  end

  def new
    @cliente = Cliente.new
    respond_with(@cliente)
  end

  def edit
  end

  def create
    @cliente = Cliente.new(cliente_params)
    flash[:notice] = 'El cliente fue creado exitosamente.' if @cliente.save
    respond_with(@cliente)
  end

  def update
    flash[:notice] = 'Elcliente fue actualizado exitosamente.' if @cliente.update(cliente_params)
    respond_with(@cliente)
  end

  def destroy
    @cliente.destroy
    respond_with(@cliente)
  end

  private
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    def cliente_params
      params.require(:cliente).permit(:nombre, :telefono, :celular, :barrio, :direccion, :refdir, :fecha, :hora, :ocacion, :valor)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
	def new
		super
	end
	def create
		super
	end
	def update
		super
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to :back, :alert => "Acceso no permitido."
    end
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/clientes/_cliente.html.erb
    <tr>
        <td><%= cliente.nombre %><%#= link_to cliente.nombre, cliente %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.celular %></td>
        <td><%= cliente.barrio %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.refdir %></td>
        <td><%= cliente.fecha %></td>
        <td><%= cliente.hora %></td>
        <td><%= cliente.ocacion %></td>
        <!--<td><%#= cliente.valor %></td>-->
        <% if can? :edit, cliente %>
            <td><%= link_to 'Ver', cliente %></td>
            <td><%= link_to 'Editar', edit_cliente_path(cliente) %></td>
        <% end %>
        <td>
        <% if can? :destroy, cliente %>
            <%= link_to 'Eliminar', cliente, method: :delete, data: { confirm: 'Borraras los datos del cliente?' } %>
        <% end %>
        </td>
    </tr>

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :telefono %><br>
    <%= f.text_field :telefono %>
  </div>
  <div class="field">
    <%= f.label :celular %><br>
    <%= f.text_field :celular %>
  </div>
  <div class="field">
    <%= f.label :barrio %><br>
    <%= f.text_field :barrio %>
  </div>
  <div class="field">
    <%= f.label :direccion %><br>
    <%= f.text_field :direccion %>
  </div>
  <div class="field">
    <%= f.label :refdir %><br>
    <%= f.text_field :refdir %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :hora %><br>
    <%= f.text_field :hora %>
  </div>
  <div class="field">
    <%= f.label :ocacion %><br>
    <%= f.text_field :ocacion %>
  </div>
  <div class="field">
    <%= f.label :valor %><br>
    <%= f.number_field :valor %>
  </div>
  <div class="actions">
    <%= f.submit "Guardar" %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editar Cliente</h1>

<%= render 'form' %>

<%= link_to 'Cancelar', @cliente %> |
<%= link_to 'Atras', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Clientes</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Teléfono</th>
      <th>Celular</th>
      <th>Barrio</th>
      <th>Dirección</th>
      <th>Referencia de la dirección</th>
      <th>Fecha</th>
      <th>Hora</th>
      <th>Ocación</th>
      <!--<th>Valor</th>-->
      <th colspan="3">Usted puede</th>
    </tr>
  </thead>

  <tbody>
    <%= render @clientes %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Cliente', new_cliente_path %>

<%# if can? :destroy, cliente %>
   <%#= link_to t('.destroy', :default => t("helpers.links.destroy")), cliente_path(client), :method => :delete,
   :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sur   e?')) }, :class => 'btn btn-mini btn-danger' %>
 <%# end %>

app/views/clientes/new.html.erb
<h1>Nuevo Cliente</h1>

<%= render 'form' %>

<%= link_to 'Atras', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @cliente.celular %>
</p>

<p>
  <strong>Barrio:</strong>
  <%= @cliente.barrio %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Refdir:</strong>
  <%= @cliente.refdir %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @cliente.fecha %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @cliente.hora %>
</p>

<p>
  <strong>Ocacion:</strong>
  <%= @cliente.ocacion %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @cliente.valor %>
</p>

<%#= link_to 'Editar', edit_cliente_path(@cliente) %> 
<%= link_to 'Atras', clientes_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'INICIO', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>  
  <li><%= link_to 'CLIENTES', clientes_path %></li>
  <li><%= link_to 'USUARIOS', users_path %></li>
  <li><%= link_to 'EDITAR CUENTA', edit_user_registration_path %></li>
  <li><%= link_to 'CERRAR SESION', destroy_user_session_path, :method=>'delete' %></li>
  <li><%= link_to current_user.name %></li>
<% else %>
  <li><%= link_to 'INICIAR SESION', new_user_session_path %></li>
  <li><%= link_to 'CREAR CUENTA', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fiesta Y Cumbia" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <link rel="shortcut icon" href="http://files.papayera-y-chirimia-medellin.webnode.es/200000014-2394b24943/fondo.jpg">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/users/_user.html.erb
<table class="table table-bordered">
	<tbody>
		<tr>
			<td><%= link_to user.name, user %></td>
			<td><%= link_to user.email, user %></td>
		</tr>
	</tbody>
</table>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Usuarios</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>Usuario</h3>
<p>Nombre: <%= @user.name if @user.name %></p>
<p>Correo: <%= @user.email if @user.email %></p>
<p>Rol: <%= @user.role if @user.role %></p>

<!--<td><%#= link_to 'Editar', edit_user_registration_path %></td>-->

app/views/visitors/index.html.erb
<html>
<head>
<style type="text/css">
body {
	background-color: #848484;
}
.Estilo2 {
	font-size: 70px;
	font-weight: bold;
}
.Estilo3 {color: #FFFF00}
.Estilo4 {color: #0000FF}
.Estilo8 {
	color: #000000;
	font-weight: bold;
	font-size: 24px;
}
.Estilo10 {color: #FF0066}
.Estilo17 {
	color: #000000;
	font-weight: bold;
	font-size: 24px;
	font-style: italic;
}
.Estilo18 {color: #CCFF66}
.Estilo19 {color: #CCFF33}
.Estilo20 {color: #CCFF00}
.Estilo21 {color: #CC00FF}
.Estilo22 {color: #FF33FF}
.Estilo23 {color: #FF9900}
.Estilo24 {color: #00FFFF}
.Estilo25 {color: #3399FF}
.Estilo26 {color: #666633}
.Estilo27 {color: #FFFF99}
.Estilo30 {color: #33FF00}
.Estilo31 {color: #FF0000}
.Estilo35 {
	color: #000000;
	font-weight: bold;
	font-size: 24px;
}
.Estilo36 {
	font-size: 24px
}
.Estilo39 {
	color: #ffff00;
	font-weight: bold;
	font-size: 36px;
}
.Estilo40 {
	font-size: 18px;
	font-weight: bold;
	font-style: italic;
	color: #CCCC00;
}
#ueles{
	background: #def;
}
sub{color: #000
}
h1{text-align: center;
}
</style>
<script src="SpryAssets/SpryMenuBar.js" type="text/javascript"></script>
<link href="SpryAssets/SpryMenuBarHorizontal.css" rel="stylesheet" type="text/css" />
<script src="Scripts/AC_RunActiveContent.js" type="text/javascript"></script>
</head>

<body>
<div align="right">
  
  <h1>FIESTA Y CUMBIA</h1>
  
</div>
<div id="ueles" align="center">
	<ul align="center">
      <p class="Estilo40">Porros, Cumbias</p>
      <p class="Estilo40">Fandangos, Mapalé</p>
      <p class="Estilo40">Sanjuanero</p>
      <p class="Estilo40">Merengues <sub>Folclóricos</sub></p>
      <p class="Estilo40">Vallenatos <sub>Tocados con clarinete u otro pito</sub></p>
	</ul>
</div>
<p align="center" class="Estilo39">&nbsp; </p>
<p align="center" class="Estilo35 Estilo36">Fiesta y cumbia es uno más de los tantos grupos folclóricos que alegra tus   
<p align="center" class="Estilo8">fiestas, desfiles, banquetes, paseos y reuniones sociales... en <u>Medellín</u>.   
<p align="center" class="Estilo8">Luchamos por mantener vivas nuestras raíces, rescatando de nuestros ancestros,  
<p align="center" class="Estilo8">las tradiciones culturales que nos representan como colombianos.  
<p align="center" class="Estilo8">Damos a conocer, de una  u otra forma,  a las nuevas generaciones,  un pasado  
<p align="center" class="Estilo8">que solo se puede apreciar  con nuestras expresiones culturales.  
<p align="center" class="Estilo17">¡<span class="Estilo18">F</span><span class="Estilo19">i</span><span class="Estilo20">e</span><span class="Estilo21">sta</span><span class="Estilo22"> y </span><span class="Estilo23">Cum</span><span class="Estilo24">bia</span><span class="Estilo25"> ale</span><span class="Estilo26">gra</span><span class="Estilo27"> tus</span> <span class="Estilo24">ev</span><span class="Estilo31">en</span><span class="Estilo30">tos</span>!  
  <div align="center"><pre class="Estilo40">Nuestro repertorio es variado:
	Vale la pena aclarar que todo este   
	repertorio suena en formato folclórico.</pre></div>
	<!--<p><%#= link_to 'Usuarios:', users_path %> <%#= User.count %> registrados</p>-->
	<p><%= link_to 'Clientes:', clientes_path %> <%= Cliente.count %> registrados</p>
</body>
</html>